In [8]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np
from scipy.stats import chi2

def ReturnDataFrame(path):
        return pd.read_csv(path, sep=',',skipinitialspace=True)      

In [19]:
# Load CVS
Path1 = '~/Dropbox/Classes/DataLab/Class/Notebook/voice.csv'
DataMatrix = ReturnDataFrame(Path1)

DataMatrix.replace({'male': -1.0, 'female': 1.0},
                    inplace=True)

DataLabels = DataMatrix['label']

DataMatrix.drop('label', axis=1, inplace=True)

# Transform to an NP Array
Data = DataMatrix.as_matrix()
Label = DataLabels.as_matrix()

In [16]:
np.mean(Data,axis = 0)

array([  0.18090661,   0.05712596,   0.18562068,   0.14045559,
         0.22476496,   0.08430937,   3.14016752,  36.56846079,
         0.89512706,   0.40821641,   0.1652818 ,   0.18090661,
         0.14280673,   0.03680181,   0.25884225,   0.82921096,
         0.05264705,   5.04727674,   4.99462969,   0.17375151])

In [20]:
Label

array([-1., -1., -1., ...,  1.,  1.,  1.])

In [22]:
Data.shape

(3168, 20)

In [30]:
Data = np.matrix(Data)
DataMean = Data - np.mean(Data,axis = 0)

In [31]:
Cov = DataMean.T*DataMean

In [33]:
n1, n2 = Data.shape

In [34]:
n1

3168

In [45]:
Cov = (1/float(n1-1))*Cov

In [46]:
Eigenvaluesc, Eigenvectorsc = np.linalg.eigh(Cov) 
idx = Eigenvaluesc.argsort()[::-1]  
Eigenvaluesc = Eigenvaluesc[idx]
Eigenvectorsc  =  Eigenvectorsc [:,idx]

In [47]:
Eigenvaluesc 

array([  5.75277668e+00,   7.30053880e-03,   2.49553337e-04,
         2.93996044e-05,   8.95736904e-06,   3.00496980e-06,
         1.53333874e-06,   1.03523527e-06,   5.04313888e-07,
         3.32852205e-07,   2.68592460e-07,   1.53046873e-07,
         8.06759327e-08,   5.65794227e-08,   4.95304721e-08,
         8.53471404e-09,   1.91937598e-09,   2.59988240e-16,
         7.87289206e-18,   2.16832855e-20])